// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tests/types/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CustomType represents a custom type for testing
type CustomType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomType) Reset() {
	*x = CustomType{}
	mi := &file_tests_types_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomType) ProtoMessage() {}

func (x *CustomType) ProtoReflect() protoreflect.Message {
	mi := &file_tests_types_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomType.ProtoReflect.Descriptor instead.
func (*CustomType) Descriptor() ([]byte, []int) {
	return file_tests_types_types_proto_rawDescGZIP(), []int{0}
}

func (x *CustomType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomType) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CustomType) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_tests_types_types_proto protoreflect.FileDescriptor

const file_tests_types_types_proto_rawDesc = "" +
	"\n" +
	"\x17tests/types/types.proto\x12\vtests.types\"P\n" +
	"\n" +
	"CustomType\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabledB2Z0github.com/kunstack/protoc-gen-flags/tests/typesb\x06proto3"

var (
	file_tests_types_types_proto_rawDescOnce sync.Once
	file_tests_types_types_proto_rawDescData []byte
)

func file_tests_types_types_proto_rawDescGZIP() []byte {
	file_tests_types_types_proto_rawDescOnce.Do(func() {
		file_tests_types_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_types_types_proto_rawDesc), len(file_tests_types_types_proto_rawDesc)))
	})
	return file_tests_types_types_proto_rawDescData
}

var file_tests_types_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tests_types_types_proto_goTypes = []any{
	(*CustomType)(nil), // 0: tests.types.CustomType
}
var file_tests_types_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests_types_types_proto_init() }
func file_tests_types_types_proto_init() {
	if File_tests_types_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_types_types_proto_rawDesc), len(file_tests_types_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_types_types_proto_goTypes,
		DependencyIndexes: file_tests_types_types_proto_depIdxs,
		MessageInfos:      file_tests_types_types_proto_msgTypes,
	}.Build()
	File_tests_types_types_proto = out.File
	file_tests_types_types_proto_goTypes = nil
	file_tests_types_types_proto_depIdxs = nil
}
