// Copyright 2021 Linka Cloud  All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-flags. DO NOT EDIT.

package tests

import (
	"github.com/kunstack/protoc-gen-flags/flags"
	"github.com/kunstack/protoc-gen-flags/types"
	"github.com/kunstack/protoc-gen-flags/utils"
	"github.com/spf13/pflag"
)

var (
	_ = pflag.NewFlagSet
	_ = utils.BuildFlagName
	_ = types.Bool
)

func (x *TestMessage) AddFlags(fs *pflag.FlagSet, prefix ...string) {
	// Hello flag generated for [(flags.value).float = {
	//     disabled: false,
	//     name: "hello",
	//     short: "h",
	//     usage: "Hello world '\"' flag",
	//     hidden: true,
	//     deprecated: true,
	//     deprecated_usage: "This flag is deprecated, use --greeting instead",
	// }]
	fs.Float32VarP(&x.Hello, utils.BuildFlagName(prefix, "hello"), "h", x.Hello, "Hello world '\"' flag")
	fs.MarkHidden("hello")
	fs.MarkDeprecated("hello", "This flag is deprecated, use --greeting instead")

	// World flag generated for [(flags.value).string = {
	//     disabled: false,
	//     name: "world",
	//     short: "",
	//     usage: "World flags (can be specified multiple times)",
	//     hidden: false,
	//     deprecated: true,
	//     deprecated_usage: "This flag is deprecated, use --target instead",
	// }]
	fs.StringVarP(&x.World, utils.BuildFlagName(prefix, "world"), "", x.World, "World flags (can be specified multiple times)")
	fs.MarkDeprecated("world", "This flag is deprecated, use --target instead")

	// Greeting flag generated for [(flags.value).string = {
	//     disabled: false,
	//     name: "greeting",
	//     short: "g",
	//     usage: "Greeting message to display",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.StringVarP(&x.Greeting, utils.BuildFlagName(prefix, "greeting"), "g", x.Greeting, "Greeting message to display")

	// Count flag generated for [(flags.value).int32 = {
	//     disabled: false,
	//     name: "count",
	//     short: "c",
	//     usage: "Number of times to repeat the message",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.Int32VarP(&x.Count, utils.BuildFlagName(prefix, "count"), "c", x.Count, "Number of times to repeat the message")

	// Verbose flag generated for [(flags.value).bool = {
	//     disabled: false,
	//     name: "verbose",
	//     short: "v",
	//     usage: "Enable verbose output",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.BoolVarP(&x.Verbose, utils.BuildFlagName(prefix, "verbose"), "v", x.Verbose, "Enable verbose output")

	// Verbose2 flag generated for [(flags.value).sfixed64 = {
	//     disabled: false,
	//     name: "verbose2",
	//     short: "V",
	//     usage: "Enable verbose output with sfixed64",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.Int64VarP(&x.Verbose2, utils.BuildFlagName(prefix, "verbose2"), "V", x.Verbose2, "Enable verbose output with sfixed64")

	// UserId flag generated for [(flags.value).int64 = {
	//     disabled: false,
	//     name: "user-id",
	//     short: "u",
	//     usage: "User ID",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.Int64VarP(&x.UserId, utils.BuildFlagName(prefix, "user-id"), "u", x.UserId, "User ID")

	// Port flag generated for [(flags.value).uint32 = {
	//     disabled: false,
	//     name: "port",
	//     short: "p",
	//     usage: "Port number",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.Uint32VarP(&x.Port, utils.BuildFlagName(prefix, "port"), "p", x.Port, "Port number")

	// Size flag generated for [(flags.value).uint64 = {
	//     disabled: false,
	//     name: "size",
	//     short: "s",
	//     usage: "Size in bytes",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.Uint64VarP(&x.Size, utils.BuildFlagName(prefix, "size"), "s", x.Size, "Size in bytes")

	// Temperature flag generated for [(flags.value).sint32 = {
	//     disabled: false,
	//     name: "temperature",
	//     short: "t",
	//     usage: "Temperature value",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.Int32VarP(&x.Temperature, utils.BuildFlagName(prefix, "temperature"), "t", x.Temperature, "Temperature value")

	// Timestamp flag generated for [(flags.value).sint64 = {
	//     disabled: false,
	//     name: "timestamp",
	//     short: "T",
	//     usage: "Timestamp value",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.Int64VarP(&x.Timestamp, utils.BuildFlagName(prefix, "timestamp"), "T", x.Timestamp, "Timestamp value")

	// Timeout flag generated for [(flags.value).fixed32 = {
	//     disabled: false,
	//     name: "timeout",
	//     short: "",
	//     usage: "Timeout in milliseconds",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.Uint32VarP(&x.Timeout, utils.BuildFlagName(prefix, "timeout"), "", x.Timeout, "Timeout in milliseconds")

	// Bandwidth flag generated for [(flags.value).fixed64 = {
	//     disabled: false,
	//     name: "bandwidth",
	//     short: "",
	//     usage: "Bandwidth in bits per second",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.Uint64VarP(&x.Bandwidth, utils.BuildFlagName(prefix, "bandwidth"), "", x.Bandwidth, "Bandwidth in bits per second")

	// Offset flag generated for [(flags.value).sfixed32 = {
	//     disabled: false,
	//     name: "offset",
	//     short: "",
	//     usage: "Offset value",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.Int32VarP(&x.Offset, utils.BuildFlagName(prefix, "offset"), "", x.Offset, "Offset value")

	// Ratio flag generated for [(flags.value).double = {
	//     disabled: false,
	//     name: "ratio",
	//     short: "r",
	//     usage: "Ratio value",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.Float64VarP(&x.Ratio, utils.BuildFlagName(prefix, "ratio"), "r", x.Ratio, "Ratio value")

	// Byte flag generated for (flags.value).bytes = {
	//  disabled: false,
	//     name: "byte",
	//     short: "b",
	//     usage: "Byte data in base64 encoding",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	//     encoding: BYTES_ENCODING_TYPE_HEX
	// }
	fs.BytesHexVarP(&x.Byte, utils.BuildFlagName(prefix, "byte"), "b", x.Byte, "Byte data in base64 encoding")

	// TestEnum flag generated for [(flags.value).enum = {
	//     disabled: false,
	//     name: "test-enum",
	//     short: "e",
	//     usage: "Test enum field",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.VarP(types.Enum(&x.TestEnum), utils.BuildFlagName(prefix, "test-enum"), "e", "Test enum field")

	// TimeoutDuration flag generated for [(flags.value).duration = {
	//     disabled: false,
	//     name: "timeout-duration",
	//     short: "d",
	//     usage: "Timeout duration (e.g., 30s, 5m, 1h)",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.VarP(types.Duration(x.TimeoutDuration), utils.BuildFlagName(prefix, "timeout-duration"), "d", "Timeout duration (e.g., 30s, 5m, 1h)")

	switch x := x.DurationChoice.(type) {
	case *TestMessage_ProcessingTime:
		// ProcessingTime flag generated for [(flags.value).duration = {
		//     disabled: false,
		//     name: "processing-time",
		//     short: "P",
		//     usage: "Processing time duration",
		//     hidden: false,
		//     deprecated: false,
		//     deprecated_usage: "",
		// }]
		fs.VarP(types.Duration(x.ProcessingTime), utils.BuildFlagName(prefix, "processing-time"), "P", "Processing time duration")

	case *TestMessage_WaitingTime:
		// WaitingTime flag generated for [(flags.value).duration = {
		//     disabled: false,
		//     name: "waiting-time",
		//     short: "w",
		//     usage: "Waiting time duration",
		//     hidden: false,
		//     deprecated: false,
		//     deprecated_usage: "",
		// }]
		fs.VarP(types.Duration(x.WaitingTime), utils.BuildFlagName(prefix, "waiting-time"), "w", "Waiting time duration")
	}
	if v, ok := interface{}(x.SimpleField).(flags.Interface); ok && x.SimpleField != nil {
		v.AddFlags(fs, "simple-field")
	}
}

func (x *SimpleMessage) AddFlags(fs *pflag.FlagSet, prefix ...string) {
	// Name flag generated for [(flags.value).string = {
	//     disabled: false,
	//     name: "name",
	//     short: "",
	//     usage: "Name parameter",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.StringVarP(&x.Name, utils.BuildFlagName(prefix, "name"), "", x.Name, "Name parameter")

}

func (x *EmptyMessage) AddFlags(fs *pflag.FlagSet, prefix ...string) {
}

func (x *WrapperMessage) AddFlags(fs *pflag.FlagSet, prefix ...string) {
	// Value flag generated for [(flags.value).float = {
	//     disabled: false,
	//     name: "value",
	//     short: "",
	//     usage: "hello",
	//     hidden: false,
	//     deprecated: false,
	//     deprecated_usage: "",
	// }]
	fs.VarP(types.Float(x.Value), utils.BuildFlagName(prefix, "value"), "", "hello")

	// value2
}

func (x *OneofMessage) AddFlags(fs *pflag.FlagSet, prefix ...string) {
	switch x := x.TestOneof.(type) {
	case *OneofMessage_StringValue:
		// StringValue flag generated for [(flags.value).string = {
		//     disabled: false,
		//     name: "string-value",
		//     short: "s",
		//     usage: "String value in oneof",
		//     hidden: false,
		//     deprecated: false,
		//     deprecated_usage: "",
		// }]
		fs.StringVarP(&x.StringValue, utils.BuildFlagName(prefix, "string-value"), "s", x.StringValue, "String value in oneof")

	case *OneofMessage_IntValue:
		// IntValue flag generated for [(flags.value).int32 = {
		//     disabled: false,
		//     name: "int-value",
		//     short: "i",
		//     usage: "Integer value in oneof",
		//     hidden: false,
		//     deprecated: false,
		//     deprecated_usage: "",
		// }]
		fs.Int32VarP(&x.IntValue, utils.BuildFlagName(prefix, "int-value"), "i", x.IntValue, "Integer value in oneof")

	case *OneofMessage_DurationValue:
		// DurationValue flag generated for [(flags.value).duration = {
		//     disabled: false,
		//     name: "duration-value",
		//     short: "d",
		//     usage: "Duration value in oneof",
		//     hidden: false,
		//     deprecated: false,
		//     deprecated_usage: "",
		// }]
		fs.VarP(types.Duration(x.DurationValue), utils.BuildFlagName(prefix, "duration-value"), "d", "Duration value in oneof")

	case *OneofMessage_BoolValue:
		// BoolValue flag generated for [(flags.value).bool = {
		//     disabled: false,
		//     name: "bool-value",
		//     short: "b",
		//     usage: "Boolean value in oneof",
		//     hidden: false,
		//     deprecated: false,
		//     deprecated_usage: "",
		// }]
		fs.BoolVarP(&x.BoolValue, utils.BuildFlagName(prefix, "bool-value"), "b", x.BoolValue, "Boolean value in oneof")
	}
}
