// Code generated by protoc-gen-flags. DO NOT EDIT.

package utils

import (
	"github.com/kunstack/protoc-gen-flags/flags"
	"github.com/kunstack/protoc-gen-flags/types"
	"github.com/kunstack/protoc-gen-flags/utils"
	"github.com/spf13/pflag"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ = pflag.NewFlagSet
	_ = utils.BuildFlagName
	_ = types.Bool
	_ = flags.Flagger(nil)
	_ = wrapperspb.String
	_ = (*durationpb.Duration)(nil)
	_ = (*timestamppb.Timestamp)(nil)
)

func (x *NestedMessage) AddFlags(fs *pflag.FlagSet, prefix ...string) {
	fs.StringVarP(&x.NestedField, utils.BuildFlagName(prefix, "nested-field"), "", x.NestedField, "Nested field parameter")

	if x.NestedTimestamp == nil {
		x.NestedTimestamp = new(timestamppb.Timestamp)
	}

	fs.VarP(types.Timestamp(x.NestedTimestamp, []string{"RFC3339", "ISO8601"}), utils.BuildFlagName(prefix, "nested-timestamp"), "", "Nested timestamp field")

}

func (x *NestedMessage) SetDefaults() {
	if x.NestedTimestamp == nil {
		x.NestedTimestamp = &timestamppb.Timestamp{Seconds: 1704067200, Nanos: 0}
	}

}
