// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tests/utils/utils/hello.proto

// buf:lint:ignore PACKAGE_VERSION_SUFFIX

package utils

import (
	_ "github.com/kunstack/protoc-gen-flags/flags"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NestedMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	NestedField string                 `protobuf:"bytes,1,opt,name=nested_field,json=nestedField,proto3" json:"nested_field,omitempty"`
	// Test timestamp with default value
	NestedTimestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=nested_timestamp,json=nestedTimestamp,proto3" json:"nested_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NestedMessage) Reset() {
	*x = NestedMessage{}
	mi := &file_tests_utils_utils_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedMessage) ProtoMessage() {}

func (x *NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tests_utils_utils_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedMessage.ProtoReflect.Descriptor instead.
func (*NestedMessage) Descriptor() ([]byte, []int) {
	return file_tests_utils_utils_hello_proto_rawDescGZIP(), []int{0}
}

func (x *NestedMessage) GetNestedField() string {
	if x != nil {
		return x.NestedField
	}
	return ""
}

func (x *NestedMessage) GetNestedTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.NestedTimestamp
	}
	return nil
}

var File_tests_utils_utils_hello_proto protoreflect.FileDescriptor

const file_tests_utils_utils_hello_proto_rawDesc = "" +
	"\n" +
	"\x1dtests/utils/utils/hello.proto\x12\x11tests.utils.utils\x1a\x17flags/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x81\x02\n" +
	"\rNestedMessage\x12N\n" +
	"\fnested_field\x18\x01 \x01(\tB+\x9aI(r&\x12\fnested-field\"\x16Nested field parameterR\vnestedField\x12\x9f\x01\n" +
	"\x10nested_timestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampBX\x9aIU\xa2\x01R\x12\x10nested-timestamp\"\x16Nested timestamp fieldB\aRFC3339B\aISO8601J\x142024-01-01T00:00:00ZR\x0fnestedTimestampB8Z6github.com/kunstack/protoc-gen-flags/tests/utils/utilsb\x06proto3"

var (
	file_tests_utils_utils_hello_proto_rawDescOnce sync.Once
	file_tests_utils_utils_hello_proto_rawDescData []byte
)

func file_tests_utils_utils_hello_proto_rawDescGZIP() []byte {
	file_tests_utils_utils_hello_proto_rawDescOnce.Do(func() {
		file_tests_utils_utils_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_utils_utils_hello_proto_rawDesc), len(file_tests_utils_utils_hello_proto_rawDesc)))
	})
	return file_tests_utils_utils_hello_proto_rawDescData
}

var file_tests_utils_utils_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tests_utils_utils_hello_proto_goTypes = []any{
	(*NestedMessage)(nil),         // 0: tests.utils.utils.NestedMessage
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_tests_utils_utils_hello_proto_depIdxs = []int32{
	1, // 0: tests.utils.utils.NestedMessage.nested_timestamp:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tests_utils_utils_hello_proto_init() }
func file_tests_utils_utils_hello_proto_init() {
	if File_tests_utils_utils_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_utils_utils_hello_proto_rawDesc), len(file_tests_utils_utils_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_utils_utils_hello_proto_goTypes,
		DependencyIndexes: file_tests_utils_utils_hello_proto_depIdxs,
		MessageInfos:      file_tests_utils_utils_hello_proto_msgTypes,
	}.Build()
	File_tests_utils_utils_hello_proto = out.File
	file_tests_utils_utils_hello_proto_goTypes = nil
	file_tests_utils_utils_hello_proto_depIdxs = nil
}
