// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tests/wrapperspb/wrapperspb.proto

package wrapperspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CustomWrapper is a test message to verify wrapperspb package name collision handling
// This should conflict with google.protobuf.wrappers which also uses "wrapperspb" as package name in Go
type CustomWrapper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomField   string                 `protobuf:"bytes,1,opt,name=custom_field,json=customField,proto3" json:"custom_field,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomWrapper) Reset() {
	*x = CustomWrapper{}
	mi := &file_tests_wrapperspb_wrapperspb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomWrapper) ProtoMessage() {}

func (x *CustomWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_tests_wrapperspb_wrapperspb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomWrapper.ProtoReflect.Descriptor instead.
func (*CustomWrapper) Descriptor() ([]byte, []int) {
	return file_tests_wrapperspb_wrapperspb_proto_rawDescGZIP(), []int{0}
}

func (x *CustomWrapper) GetCustomField() string {
	if x != nil {
		return x.CustomField
	}
	return ""
}

func (x *CustomWrapper) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_tests_wrapperspb_wrapperspb_proto protoreflect.FileDescriptor

const file_tests_wrapperspb_wrapperspb_proto_rawDesc = "" +
	"\n" +
	"!tests/wrapperspb/wrapperspb.proto\x12\x10tests.wrapperspb\"H\n" +
	"\rCustomWrapper\x12!\n" +
	"\fcustom_field\x18\x01 \x01(\tR\vcustomField\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05valueBBZ@github.com/kunstack/protoc-gen-flags/tests/wrapperspb;wrapperspbb\x06proto3"

var (
	file_tests_wrapperspb_wrapperspb_proto_rawDescOnce sync.Once
	file_tests_wrapperspb_wrapperspb_proto_rawDescData []byte
)

func file_tests_wrapperspb_wrapperspb_proto_rawDescGZIP() []byte {
	file_tests_wrapperspb_wrapperspb_proto_rawDescOnce.Do(func() {
		file_tests_wrapperspb_wrapperspb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_wrapperspb_wrapperspb_proto_rawDesc), len(file_tests_wrapperspb_wrapperspb_proto_rawDesc)))
	})
	return file_tests_wrapperspb_wrapperspb_proto_rawDescData
}

var file_tests_wrapperspb_wrapperspb_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tests_wrapperspb_wrapperspb_proto_goTypes = []any{
	(*CustomWrapper)(nil), // 0: tests.wrapperspb.CustomWrapper
}
var file_tests_wrapperspb_wrapperspb_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests_wrapperspb_wrapperspb_proto_init() }
func file_tests_wrapperspb_wrapperspb_proto_init() {
	if File_tests_wrapperspb_wrapperspb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_wrapperspb_wrapperspb_proto_rawDesc), len(file_tests_wrapperspb_wrapperspb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_wrapperspb_wrapperspb_proto_goTypes,
		DependencyIndexes: file_tests_wrapperspb_wrapperspb_proto_depIdxs,
		MessageInfos:      file_tests_wrapperspb_wrapperspb_proto_msgTypes,
	}.Build()
	File_tests_wrapperspb_wrapperspb_proto = out.File
	file_tests_wrapperspb_wrapperspb_proto_goTypes = nil
	file_tests_wrapperspb_wrapperspb_proto_depIdxs = nil
}
