// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: tests/utils/hello.proto

// buf:lint:ignore PACKAGE_VERSION_SUFFIX

package utils

import (
	_ "github.com/kunstack/protoc-gen-flags/flags"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Test timestamp with default value
	CreatedAt     []*timestamppb.Timestamp `protobuf:"bytes,2,rep,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleMessage) Reset() {
	*x = SimpleMessage{}
	mi := &file_tests_utils_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMessage) ProtoMessage() {}

func (x *SimpleMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tests_utils_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMessage.ProtoReflect.Descriptor instead.
func (*SimpleMessage) Descriptor() ([]byte, []int) {
	return file_tests_utils_hello_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SimpleMessage) GetCreatedAt() []*timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_tests_utils_hello_proto protoreflect.FileDescriptor

const file_tests_utils_hello_proto_rawDesc = "" +
	"\n" +
	"\x17tests/utils/hello.proto\x12\vtests.utils\x1a\x11flags/flags.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcf\x01\n" +
	"\rSimpleMessage\x12/\n" +
	"\x04name\x18\x01 \x01(\tB\x1b\x9aI\x18r\x16\x12\x04name\"\x0eName parameterR\x04name\x12\x8c\x01\n" +
	"\n" +
	"created_at\x18\x02 \x03(\v2\x1a.google.protobuf.TimestampBQ\x9aIN\x8a\x01K\x92\x01H\x12\n" +
	"created-at\"\x12Creation timestampB\aRFC3339B\aISO8601J\x142023-01-01T00:00:00ZR\tcreatedAtB2Z0github.com/kunstack/protoc-gen-flags/tests/utilsb\x06proto3"

var (
	file_tests_utils_hello_proto_rawDescOnce sync.Once
	file_tests_utils_hello_proto_rawDescData []byte
)

func file_tests_utils_hello_proto_rawDescGZIP() []byte {
	file_tests_utils_hello_proto_rawDescOnce.Do(func() {
		file_tests_utils_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tests_utils_hello_proto_rawDesc), len(file_tests_utils_hello_proto_rawDesc)))
	})
	return file_tests_utils_hello_proto_rawDescData
}

var file_tests_utils_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tests_utils_hello_proto_goTypes = []any{
	(*SimpleMessage)(nil),         // 0: tests.utils.SimpleMessage
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_tests_utils_hello_proto_depIdxs = []int32{
	1, // 0: tests.utils.SimpleMessage.created_at:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tests_utils_hello_proto_init() }
func file_tests_utils_hello_proto_init() {
	if File_tests_utils_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tests_utils_hello_proto_rawDesc), len(file_tests_utils_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_utils_hello_proto_goTypes,
		DependencyIndexes: file_tests_utils_hello_proto_depIdxs,
		MessageInfos:      file_tests_utils_hello_proto_msgTypes,
	}.Build()
	File_tests_utils_hello_proto = out.File
	file_tests_utils_hello_proto_goTypes = nil
	file_tests_utils_hello_proto_depIdxs = nil
}
